
package test.getobjects;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GetObjects", targetNamespace = "http://www.resourcesmanager.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetObjects {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.millicom.rm.sync.client.click.getobjects.GetObjectsResponse
     * @throws GetObjectsFault
     */
    @WebMethod(operationName = "GetObjects", action = "http://www.resourcesmanager.com/GetObjects")
    @WebResult(name = "GetObjectsResponse", targetNamespace = "http://xmlns.tigo.com/TigoFS/FieldServiceProxy/GetObjectsResponse/V1/schema", partName = "parameters")
    public GetObjectsResponse getObjects(
        @WebParam(name = "GetObjectsRequest", targetNamespace = "http://xmlns.tigo.com/TigoFS/FieldServiceProxy/GetObjectsRequest/V1/schema", partName = "parameters")
        GetObjectsRequest parameters)
        throws GetObjectsFault
    ;

}
