
package test.getobjects;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "resourcesManagerFault", targetNamespace = "http://xmlns.tigo.com/TigoFS/ResourcesManagerFault/V1/schema")
public class GetObjectsFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ResourcesManagerFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public GetObjectsFault(String message, ResourcesManagerFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public GetObjectsFault(String message, ResourcesManagerFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.millicom.rm.sync.client.click.getobjects.ResourcesManagerFault
     */
    public ResourcesManagerFault getFaultInfo() {
        return faultInfo;
    }

}
