
package test;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ResponseHeader", targetNamespace = "http://xmlns.tigo.com/ResponseHeader/V3")
public class GeneralResponseMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ResponseHeader faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public GeneralResponseMsg(String message, ResponseHeader faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public GeneralResponseMsg(String message, ResponseHeader faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: test.ResponseHeader
     */
    public ResponseHeader getFaultInfo() {
        return faultInfo;
    }

}
