
package test;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetUserDetailsPortTypeSOAP12BindingQSService", targetNamespace = "http://xmlns.tigo.com/MFS/GetUserDetails/V1", wsdlLocation = "file:/C:/Users/Administrador/Desktop/firm/GetUserDetails_PUB_1.wsdl")
public class GetUserDetailsPortTypeSOAP12BindingQSService
    extends Service
{

    private final static URL GETUSERDETAILSPORTTYPESOAP12BINDINGQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETUSERDETAILSPORTTYPESOAP12BINDINGQSSERVICE_EXCEPTION;
    private final static QName GETUSERDETAILSPORTTYPESOAP12BINDINGQSSERVICE_QNAME = new QName("http://xmlns.tigo.com/MFS/GetUserDetails/V1", "GetUserDetailsPortTypeSOAP12BindingQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Administrador/Desktop/firm/GetUserDetails_PUB_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETUSERDETAILSPORTTYPESOAP12BINDINGQSSERVICE_WSDL_LOCATION = url;
        GETUSERDETAILSPORTTYPESOAP12BINDINGQSSERVICE_EXCEPTION = e;
    }

    public GetUserDetailsPortTypeSOAP12BindingQSService() {
        super(__getWsdlLocation(), GETUSERDETAILSPORTTYPESOAP12BINDINGQSSERVICE_QNAME);
    }

    public GetUserDetailsPortTypeSOAP12BindingQSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETUSERDETAILSPORTTYPESOAP12BINDINGQSSERVICE_QNAME, features);
    }

    public GetUserDetailsPortTypeSOAP12BindingQSService(URL wsdlLocation) {
        super(wsdlLocation, GETUSERDETAILSPORTTYPESOAP12BINDINGQSSERVICE_QNAME);
    }

    public GetUserDetailsPortTypeSOAP12BindingQSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETUSERDETAILSPORTTYPESOAP12BINDINGQSSERVICE_QNAME, features);
    }

    public GetUserDetailsPortTypeSOAP12BindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetUserDetailsPortTypeSOAP12BindingQSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetUserDetailsPortType
     */
    @WebEndpoint(name = "GetUserDetailsPortTypeSOAP12BindingQSPort")
    public GetUserDetailsPortType getGetUserDetailsPortTypeSOAP12BindingQSPort() {
        return super.getPort(new QName("http://xmlns.tigo.com/MFS/GetUserDetails/V1", "GetUserDetailsPortTypeSOAP12BindingQSPort"), GetUserDetailsPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetUserDetailsPortType
     */
    @WebEndpoint(name = "GetUserDetailsPortTypeSOAP12BindingQSPort")
    public GetUserDetailsPortType getGetUserDetailsPortTypeSOAP12BindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.tigo.com/MFS/GetUserDetails/V1", "GetUserDetailsPortTypeSOAP12BindingQSPort"), GetUserDetailsPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETUSERDETAILSPORTTYPESOAP12BINDINGQSSERVICE_EXCEPTION!= null) {
            throw GETUSERDETAILSPORTTYPESOAP12BINDINGQSSERVICE_EXCEPTION;
        }
        return GETUSERDETAILSPORTTYPESOAP12BINDINGQSSERVICE_WSDL_LOCATION;
    }

}
