
package source;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GenericPayments", targetNamespace = "http://xmlns.tigo.com/MFS/GenericPayments/V1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GenericPayments {


    /**
     * 
     * @param parameters
     * @return
     *     returns source.PayBillResponse
     * @throws PayBillFaultMessage
     */
    @WebMethod(operationName = "PayBill", action = "http://xmlns.tigo.com/MFS/GenericPayments/PayBill")
    @WebResult(name = "PayBillResponse", targetNamespace = "http://xmlns.tigo.com/MFS/GenericPayments/PayBillResponse/V1/schema", partName = "parameters")
    public PayBillResponse payBill(
        @WebParam(name = "PayBillRequest", targetNamespace = "http://xmlns.tigo.com/MFS/GenericPayments/PayBillRequest/V1/schema", partName = "parameters")
        PayBillRequest parameters)
        throws PayBillFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns source.ViewBillResponse
     * @throws ViewBillFaultMessage
     */
    @WebMethod(operationName = "ViewBill", action = "http://xmlns.tigo.com/MFS/GenericPayments/ViewBill")
    @WebResult(name = "ViewBillResponse", targetNamespace = "http://xmlns.tigo.com/MFS/GenericPayments/ViewBillResponse/V1/schema", partName = "parameters")
    public ViewBillResponse viewBill(
        @WebParam(name = "ViewBillRequest", targetNamespace = "http://xmlns.tigo.com/MFS/GenericPayments/ViewBillRequest/V1/schema", partName = "parameters")
        ViewBillRequest parameters)
        throws ViewBillFaultMessage
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns source.RevertPayResponse
     * @throws RevertPayFaultMessage
     */
    @WebMethod(operationName = "RevertPay", action = "http://xmlns.tigo.com/MFS/GenericPayments/RevertPay")
    @WebResult(name = "RevertPayResponse", targetNamespace = "http://xmlns.tigo.com/MFS/GenericPayments/RevertPayResponse/V1/schema", partName = "parameters")
    public RevertPayResponse revertPay(
        @WebParam(name = "RevertPayRequest", targetNamespace = "http://xmlns.tigo.com/MFS/GenericPayments/RevertPayRequest/V1/schema", partName = "parameters")
        RevertPayRequest parameters)
        throws RevertPayFaultMessage
    ;

}
