
package source;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GenericPaymentsSOAPQSService", targetNamespace = "http://xmlns.tigo.com/MFS/GenericPayments/V1", wsdlLocation = "http://192.168.105.190:8011/MFS/GenericPayments/V1?wsdl")
public class GenericPaymentsSOAPQSService
    extends Service
{

    private final static URL GENERICPAYMENTSSOAPQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException GENERICPAYMENTSSOAPQSSERVICE_EXCEPTION;
    private final static QName GENERICPAYMENTSSOAPQSSERVICE_QNAME = new QName("http://xmlns.tigo.com/MFS/GenericPayments/V1", "GenericPaymentsSOAPQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.105.190:8011/MFS/GenericPayments/V1?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GENERICPAYMENTSSOAPQSSERVICE_WSDL_LOCATION = url;
        GENERICPAYMENTSSOAPQSSERVICE_EXCEPTION = e;
    }

    public GenericPaymentsSOAPQSService() {
        super(__getWsdlLocation(), GENERICPAYMENTSSOAPQSSERVICE_QNAME);
    }

    public GenericPaymentsSOAPQSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GENERICPAYMENTSSOAPQSSERVICE_QNAME, features);
    }

    public GenericPaymentsSOAPQSService(URL wsdlLocation) {
        super(wsdlLocation, GENERICPAYMENTSSOAPQSSERVICE_QNAME);
    }

    public GenericPaymentsSOAPQSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GENERICPAYMENTSSOAPQSSERVICE_QNAME, features);
    }

    public GenericPaymentsSOAPQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GenericPaymentsSOAPQSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GenericPayments
     */
    @WebEndpoint(name = "GenericPaymentsSOAPQSPort")
    public GenericPayments getGenericPaymentsSOAPQSPort() {
        return super.getPort(new QName("http://xmlns.tigo.com/MFS/GenericPayments/V1", "GenericPaymentsSOAPQSPort"), GenericPayments.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GenericPayments
     */
    @WebEndpoint(name = "GenericPaymentsSOAPQSPort")
    public GenericPayments getGenericPaymentsSOAPQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.tigo.com/MFS/GenericPayments/V1", "GenericPaymentsSOAPQSPort"), GenericPayments.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GENERICPAYMENTSSOAPQSSERVICE_EXCEPTION!= null) {
            throw GENERICPAYMENTSSOAPQSSERVICE_EXCEPTION;
        }
        return GENERICPAYMENTSSOAPQSSERVICE_WSDL_LOCATION;
    }

}
