
package source;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "PayBillFault", targetNamespace = "http://xmlns.tigo.com/MFS/PayBillFault/V1/schema")
public class PayBillFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PayBillFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PayBillFaultMessage(String message, PayBillFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public PayBillFaultMessage(String message, PayBillFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: source.PayBillFault
     */
    public PayBillFault getFaultInfo() {
        return faultInfo;
    }

}
