
package source;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "RevertPayFault", targetNamespace = "http://xmlns.tigo.com/MFS/RevertPayFault/V1/schema")
public class RevertPayFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private RevertPayFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public RevertPayFaultMessage(String message, RevertPayFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public RevertPayFaultMessage(String message, RevertPayFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: source.RevertPayFault
     */
    public RevertPayFault getFaultInfo() {
        return faultInfo;
    }

}
