package hackerrank.java.introduction;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class JavaRegex2DuplicateWords {
    public static void main(String[] args) {
	String text= "<ns2:GetObjectsResponse xmlns:ns2=\"com.millicom.rm.sync.client.click.getobjects\" xmlns=\"http://xmlns.tigo.com/TigoFS/FieldServiceProxy/GetObjectsResponse/V1/schema\">\n"
			+ "    <Objects>\n"
			+ "        <Object xmlns:sch=\"http://xmlns.tigo.com/TigoFS/FieldServiceProxy/GetObjectsResponse/V1/schema\">\n"
			+ "            <GetObjectsResponse:GetObjectsResponse xmlns=\"http://www.clicksoftware.com\" xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:GetObjectsResponse=\"http://www.clicksoftware.com\">\n"
			+ "                <Objects>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>NUEVO02</ID>\n"
			+ "                        <Description>VERIFICADOQA02</Description>\n"
			+ "                        <Unit>Meters</Unit>\n"
			+ "                        <QuantityInStock>6</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-NUEVO02-1594568665245cd9b5fcf-9fd8-41de-847f-5aaa4b256ce6</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>HME0002878</ID>\n"
			+ "                        <Description>DCX-905 ARRIS STB HD</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-HME0002878-15916310089737e61814e-817b-4352-80d2-1f0db5a4120b</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>HME0002878</ID>\n"
			+ "                        <Description>DCX-905 ARRIS STB HD</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-HME0002878-1591202997592418468f3-cb86-45a2-97cb-f8eef50051fb</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>NUEVO03</ID>\n"
			+ "                        <Description>VERIFICADOQA03</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>1</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-NUEVO03-159467316978876f5430b-fc73-498f-ad5f-b81f201aa86a</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>MARZO1303-1</ID>\n"
			+ "                        <Description>DESC ROUTER NEGRO INALAMBRICO</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-MARZO1303-1-1588606150837489e8956-8596-453c-8ea7-5f963dfe6fb6</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>MED006</ID>\n"
			+ "                        <Description>DESCMED006</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-MED006-1585864553682ca502ae7-f118-445c-8744-c3156cdf48ee</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>HME0002878</ID>\n"
			+ "                        <Description>DCX-905 ARRIS STB HD</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-HME0002878-1591646808060084dd1fd-9e21-4b44-8bfd-266cbb110e6c</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>HME0002878</ID>\n"
			+ "                        <Description>DCX-905 ARRIS STB HD</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-HME0002878-1593650621708e944618e-402c-4e4a-8db7-ddc3d546fe23</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>HME0002878</ID>\n"
			+ "                        <Description>DCX-905 ARRIS STB HD</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-HME0002878-1591646808060f172f6d1-f949-48fa-821c-225f030dca5f</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>MARZO1303-1</ID>\n"
			+ "                        <Description>DESC ROUTER NEGRO INALAMBRICO</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-MARZO1303-1-15886061508383f1a098f-f8ee-4816-88fc-a890cd3b78dd</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>NUEVO03</ID>\n"
			+ "                        <Description>VERIFICADOQA03</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-NUEVO03-159456825950852af6a2b-41ae-406d-ab57-c590abdc1540</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>NUEVO03</ID>\n"
			+ "                        <Description>VERIFICADOQA03</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-NUEVO03-159434571323402584209-97a9-4509-b27f-c447cf0c2585</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>MED002</ID>\n"
			+ "                        <Description>NOMMED002</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>888-cod001-1586018400375e241d559-9bc9-47d9-ac1d-155357A0001</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>NUEVO10</ID>\n"
			+ "                        <Description>VERIFICADOQA10</Description>\n"
			+ "                        <Unit>Meters</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-NUEVO10-1594481014814eb56a315-1f6e-4a68-987e-6c85ea2026b8</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>MED002</ID>\n"
			+ "                        <Description>NOMMED002</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>888-cod001-1586018400375e241d559-9bc9-47d9-ac1d-155357A0003</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>NUEVO10</ID>\n"
			+ "                        <Description>VERIFICADOQA10</Description>\n"
			+ "                        <Unit>Meters</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-NUEVO10-1594837628997c5bf611b-b022-4139-820d-60934a709ebd</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>ACC0001137</ID>\n"
			+ "                        <Description>RG6 CABLE WITH MESSENGER</Description>\n"
			+ "                        <Unit>Meters</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-ACC0001137-15930272318486ba261c8-166f-4385-bcc8-36ad7d0f7a86</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>MARZO1303-1</ID>\n"
			+ "                        <Description>DESC ROUTER NEGRO INALAMBRICO</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-MARZO1303-1-1585761635222dad34a33-21ba-4bb0-9e36-16d71a69afaf</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>HME0002878</ID>\n"
			+ "                        <Description>DCX-905 ARRIS STB HD</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-HME0002878-159104837927888741df6-9644-4c0a-b1a5-61ba9465380e</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>NUEVO03</ID>\n"
			+ "                        <Description>VERIFICADOQA03</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-NUEVO03-1594673169788ffb6bf39-ed91-4661-9ab8-fa3288ce354b</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>MARZO1303-1</ID>\n"
			+ "                        <Description>DESC ROUTER NEGRO INALAMBRICO</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-MARZO1303-1-15886061508378106ae6a-4599-40ed-a7fe-ac724071016d</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>MARZO1303-1</ID>\n"
			+ "                        <Description>DESC ROUTER NEGRO INALAMBRICO</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-MARZO1303-1-1585766302600556ff32b-b9cd-46af-a6c2-f553da05f6d2</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>MARZO1303-1</ID>\n"
			+ "                        <Description>DESC ROUTER NEGRO INALAMBRICO</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-MARZO1303-1-15886061508381e806ceb-657e-4d34-af8a-9e0f0875a52b</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>MARZO1303-1</ID>\n"
			+ "                        <Description>DESC ROUTER NEGRO INALAMBRICO</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-MARZO1303-1-1588606150838df8253d9-816d-434a-bced-47e473e1f9f5</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>HME0002878</ID>\n"
			+ "                        <Description>DCX-905 ARRIS STB HD</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-HME0002878-1591211666357b8a1b525-cb30-43fe-be9c-500d6089aa15</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>NUEVO03</ID>\n"
			+ "                        <Description>VERIFICADOQA03</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-NUEVO03-1594345713234b091f1c0-c32f-43fd-823f-e0e9a67385ac</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>NUEVO03</ID>\n"
			+ "                        <Description>VERIFICADOQA03</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-NUEVO03-15943457132348c435eac-fe2c-439c-859b-e31f7693686a</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>HME0002878</ID>\n"
			+ "                        <Description>DCX-905 ARRIS STB HD</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-HME0002878-1591631008972ca4cb9ee-57f2-4516-ba4c-3b70fd522008</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>MED002</ID>\n"
			+ "                        <Description>NOMMED002</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>888-cod001-1586018400375e241d559-9bc9-47d9-ac1d-155357A0002</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>MED002</ID>\n"
			+ "                        <Description>NOMMED002</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>888-cod001-1586018400375e241d559-9bc9-47d9-ac1d-155357A0004</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>NUEVO10</ID>\n"
			+ "                        <Description>VERIFICADOQA10</Description>\n"
			+ "                        <Unit>Meters</Unit>\n"
			+ "                        <QuantityInStock>1</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-NUEVO10-159483762899706a4d83e-b590-4ab9-9c78-53aa1a71d941</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>MED005</ID>\n"
			+ "                        <Description>DESCMED005</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-MED005-1585864553681f26d8dec-d155-41d5-999b-2d63a7f23f69</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>HME0002878</ID>\n"
			+ "                        <Description>DCX-905 ARRIS STB HD</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-HME0002878-1591646808060a2ae2b35-e244-4309-a765-5596f0c03d37</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>MARZO1303-1</ID>\n"
			+ "                        <Description>DESC ROUTER NEGRO INALAMBRICO</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-MARZO1303-1-15886061508371ef84ac2-4652-4d42-8eb1-8a766568529c</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>NUEVO02</ID>\n"
			+ "                        <Description>VERIFICADOQA02</Description>\n"
			+ "                        <Unit>Meters</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-NUEVO02-159434571323313ee4b85-f5b3-46f8-88cd-9e3e1e219e51</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>HME0002878</ID>\n"
			+ "                        <Description>DCX-905 ARRIS STB HD</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-HME0002878-15916468080608f68f276-c011-4cd0-b796-4c1f147bcaca</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>HME0002878</ID>\n"
			+ "                        <Description>DCX-905 ARRIS STB HD</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-HME0002878-15913925678676bd958a8-fa20-421f-9a7e-ac09ff0eb7da</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>MARZO1303-1</ID>\n"
			+ "                        <Description>DESC ROUTER NEGRO INALAMBRICO</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-MARZO1303-1-15886061508381232175a-2082-4900-be75-f2db5dfb8070</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>NUEVO03</ID>\n"
			+ "                        <Description>VERIFICADOQA03</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-NUEVO03-15945682595080fc26817-2738-45b5-afce-6341fca328c7</ExternalRefID>\n"
			+ "                    </Object>\n"
			+ "                    <Object d3p1:type=\"MCPartsInStock\" xmlns:d3p1=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
			+ "                        <ID>NUEVO03</ID>\n"
			+ "                        <Description>VERIFICADOQA03</Description>\n"
			+ "                        <Unit>Units</Unit>\n"
			+ "                        <QuantityInStock>0</QuantityInStock>\n"
			+ "                        <ExternalRefID>669-NUEVO03-1594345713234a235a4f5-357d-4b80-a1a1-bc0c65d53da1</ExternalRefID>\n"
			+ "                    </Object>\n" + "                </Objects>\n"
			+ "            </GetObjectsResponse:GetObjectsResponse>\n" + "        </Object>\n"
			+ "    </Objects>\n" + "</ns2:GetObjectsResponse>\n";

	String regex= "<Object .+=\"MCPartsInStock\"[.\\n<>=:\\-\" /\\w]*</Object>";
	Pattern pattern = Pattern.compile(regex);
	Matcher matcher = pattern.matcher(text);
	while(matcher.find()){
	    String group = matcher.group();
	    System.out.println(group);
	}

    }

    public void test() {
	String regex = "\\b(\\w+)(\\s+\\1\\b)+";
	String phrase = "Goodbye bye bye world world world";
	Pattern pattern = Pattern.compile(regex, Pattern.CASE_INSENSITIVE);
	Matcher matcher = pattern.matcher(phrase);
	while (matcher.find()) {
	    String group = matcher.group();
	    phrase = phrase.replaceAll(group, matcher.group(1));
	}
	System.out.println(phrase);
    }
}
